# File: data_brachi.yaml
# Author: Mia Scoblic
# Date: 2025-08-15
# Description:
#     This file points to an Excel file in the 'data' folder and defines the Excel data layout and normalization techniques

excel_path: data/brachi.xlsx

schema:
  # define excel header
  header: 0

  # inputs:
  input_cols: [x0, y0, xf, yf]

  # outputs: x trajectory, y trajectory
  output_slices:
    - [x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23, x24]
    - [y1, y2, y3, y4, y5, y6, y7, y8, y9, y10, y11, y12, y13, y14, y15, y16, y17, y18, y19, y20, y21, y22, y23, y24]

  # infer the number of traj points based on output, flexible if the data range changes
  infer_T_from_outputs: true
  K: 2

# choose the mode of normalization (standardize/
# include_indices allows you to choose a subset of inputs to include in standardization
normalization:
  inputs:
    mode: standardize
    include_indices: [0, 1, 2, 3]
  outputs:
    mode: standardize               # “none” if you prefer physical units

task_name: brachi
