# File: model_collision_heading.yaml
# Author: Mia Scoblic
# Date: 2025-08-15
# Description:
#     This file creates the neural network architecture

# type of model (src/models.py)
kind: ffn
ffn:
  hidden_dim: 512
  n_hidden: 4
  activation: gelu        # relu/gelu/tanh
  # randomly turn of neurons, improves generalization and reduces overfitting
  dropout: 0.0
