# File: data_collision.yaml
# Author: Mia Scoblic
# Date: 2025-08-15
# Description:
#     This file points to an Excel file in the 'data' folder and defines the Excel data layout and normalization techniques

excel_path: data/CA3D/CA3D_variable_radius.xlsx

schema:
  # define excel header
  header: 0

  # inputs:
  input_cols: [x0, y0, z0, xf, yf, zf, ox, oy, oz, radius, vxinit, vyinit, vzinit]

  # outputs: x trajectory, y trajectory
  output_slices:
    - [x2, x3, x4, x5, x6, x7, x8]
    - [y2, y3, y4, y5, y6, y7, y8]
    - [z2, z3, z4, z5, z6, z7, z8]

  # infer the number of traj points based on output, flexible if the data range changes
  infer_T_from_outputs: true
  K: 3

# choose the mode of normalization (standardize/
# include_indices allows you to choose a subset of inputs to include in standardization
normalization:
  inputs:
    mode: standardize
    include_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  outputs:
    mode: standardize

task_name: collision_3D_random_radii
