# File: data_airspace.yaml
# Author: Mia Scoblic
# Date: 2025-08-15
# Description:
#     This file points to an Excel file in the 'data' folder and defines the Excel data layout and normalization techniques

excel_path: data/airspaceOneHot.xlsx

schema:
  # define excel header
  header: 0

  # inputs: x0, y0, one-hot segment (6 columns)
  input_cols: [x0, y0, s1, s2, s3, s4, s5, s6]

  # outputs: x trajectory, y trajectory
  output_slices:
    - [x1, x2, x3, x4, x5, x6, x7, x8, x9]
    - [y1, y2, y3, y4, y5, y6, y7, y8, y9]


  # infer the number of traj points based on output, flexible if the data range changes
  infer_T_from_outputs: true
  K: 2

# choose the mode of normalization (standardize/
# include_indices allows you to choose a subset of inputs to include in standardization
normalization:
  inputs:
    mode: standardize
    include_indices: [0, 1]      # only standardize x0, y0
  outputs:
    mode: standardize

task_name: airspace
